export const demoDb: string[] | any = [
  'www.youtube.com/watch?v=B74AK0MHxOA',
  'www.youtube.com/watch?v=o9YGg_ZfvGM',
  'www.youtube.com/watch?v=5TMLa14s70s',
  'www.youtube.com/watch?v=fjdyDwU4W9s',
  'www.youtube.com/watch?v=ZKsM_xqYXLg',
  'www.youtube.com/watch?v=xBO_37evRBM',
  'www.youtube.com/watch?v=0BA-cAmr0jQ',
  'www.youtube.com/watch?v=rRIc7sbvb5U',
  'www.youtube.com/watch?v=2F3wpKRdr2E',
  'www.youtube.com/watch?v=sQzG-gUmifI',
  'www.youtube.com/watch?v=5vKCNoSoTns',
  'www.youtube.com/watch?v=_3ue6dFYkOk',
  'www.youtube.com/watch?v=9u3MOvWuLH4',
  'www.youtube.com/watch?v=lCiwUXQ-bmc',
  'www.youtube.com/watch?v=6saQS3yZAn0',
];
