export const demoDb: string[] | any = [
  'https://www.youtube.com/watch?v=5X-jxn_OlIs',
  'https://www.youtube.com/watch?v=qvsgGtivCgs',
  'https://www.youtube.com/watch?v=6BK72_q9d1A',
  'www.youtube.com/watch?v=B74AK0MHxOA',
  'https://www.youtube.com/watch?v=nZaZ2dB6pow',
  'www.youtube.com/watch?v=5TMLa14s70s',
  'www.youtube.com/watch?v=fjdyDwU4W9s',
  'https://www.youtube.com/watch?v=BKviRM0KF2A',
  'https://www.youtube.com/watch?v=aWzlQ2N6qqg',
  'https://www.youtube.com/watch?v=Go8nTmfrQd8',
  'https://www.youtube.com/watch?v=6CKcqIahedc',
  'www.youtube.com/watch?v=_3ue6dFYkOk',
  'https://www.youtube.com/watch?v=HrzdCKyjK2M',
  'https://www.youtube.com/watch?v=ajTTZ7iy6Ls',
  'https://www.youtube.com/watch?v=9ix7TUGVYIo',
  'https://www.youtube.com/watch?v=wwesofbMExI',
  'https://www.youtube.com/watch?v=iD3qXGkgAsI',
  'https://www.youtube.com/watch?v=JfVOs4VSpmA',
  'www.youtube.com/watch?v=WEfbhOG8VRY',
  'https://www.youtube.com/watch?v=3bl63l4miDU',
  'https://www.youtube.com/watch?v=_w6Uxclog7E',
  // 'https://www.youtube.com/watch?v=inVC_PZ45VM',
  // 'https://www.youtube.com/watch?v=gNtJ4HdMavo',
  // 'https://www.youtube.com/watch?v=a1a2R_0OgPA',
  // 'https://www.youtube.com/watch?v=0kL-auZQLzY',
  // 'https://www.youtube.com/watch?v=6pfhlKndNvM',
  // 'https://www.youtube.com/watch?v=yFgSYXu4V1c',
  // 'https://www.youtube.com/watch?v=HbfCbGffQbo',
  // 'https://www.youtube.com/watch?v=VEynG2dWDyw',
  // 'https://www.youtube.com/watch?v=vLxOcATqddw',
  // 'https://www.youtube.com/watch?v=h0eTDgUZZCI',
  // 'https://www.youtube.com/watch?v=tKJbSwqK6jY',
  // 'https://www.youtube.com/watch?v=XfD4_QLfkws',
  // 'https://www.youtube.com/watch?v=4gdffm7bUmo',
  // 'https://www.youtube.com/watch?v=z9ZNu-tgJzQ',
  // 'https://www.youtube.com/watch?v=0f8WzWs_HSI',

  // 'https://www.youtube.com/watch?v=2dmUdLhHr0M',
  // 'https://www.youtube.com/watch?v=2onQ2gQDumM',
  // 'https://www.youtube.com/watch?v=qNy-0jz66EM',
  // 'https://www.youtube.com/watch?v=FliLmY45XPY',
  // 'https://www.youtube.com/watch?v=MuNmVP-rr-o',
  // 'https://youtu.be/2QSukL7dl5o',
  // 'https://youtu.be/h5Q1rqUXdNk',
  // 'https://vimeo.com/712760573',
  // 'https://vimeo.com/680668269',
  // 'https://vimeo.com/672931094',
  // 'https://youtu.be/2QSukL7dl5o',
];
